---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cardekco/public_html/
    - /bin/cp -rn public/* $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install
    - /usr/bin/php artisan migrate --force --seed